// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFMvLr3RjmAEtVH7rzsM24MIZYj53iKpE',
    appId: '1:827404526719:web:28217fd80ec65ecd370b4a',
    messagingSenderId: '827404526719',
    projectId: 'fruitvis',
    authDomain: 'fruitvis.firebaseapp.com',
    storageBucket: 'fruitvis.appspot.com',
    measurementId: 'G-9TZFM1WS09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjSigP0IsvLXu85zyqr02eRLcFbyUOCs',
    appId: '1:827404526719:android:92d0d4740f328b2b370b4a',
    messagingSenderId: '827404526719',
    projectId: 'fruitvis',
    storageBucket: 'fruitvis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxT87RXrw5utolXbqZaYYlFh9Fee1hRgI',
    appId: '1:827404526719:ios:ac4a601f9f9e9ccf370b4a',
    messagingSenderId: '827404526719',
    projectId: 'fruitvis',
    storageBucket: 'fruitvis.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxT87RXrw5utolXbqZaYYlFh9Fee1hRgI',
    appId: '1:827404526719:ios:3b36a7ec471e75b5370b4a',
    messagingSenderId: '827404526719',
    projectId: 'fruitvis',
    storageBucket: 'fruitvis.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
